<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\epg\Controller\epgController;
use Drupal\epg\Model\Content\programmeFilter;

function epg_cron() {
    ini_set('memory_limit', '1024M');
    $lastImport = \Drupal::state()->get('epg.last_import', 0);
    $lastExport = \Drupal::state()->get('epg.last_export', 0);
    $lastUpdate = \Drupal::state()->get('epg.last_update', 0);
    $requestTime = \Drupal::time()->getRequestTime();
    $epgController = new epgController();
    if (($requestTime - $lastImport) > 43200) {
        $epgController->importFeed();
        \Drupal::state()->set('epg.last_import', $requestTime);
    }
    if (($requestTime - $lastExport) > 3600) {
        $epgController->createXML();
        \Drupal::state()->set('epg.last_export', $requestTime);
    }
    if (($requestTime - $lastUpdate) > 300) {
        $epgController->importProviderData();
        \Drupal::state()->set('epg.last_update', $requestTime);
    }
}

function epg_node_update(EntityInterface $entity) {
    if($entity->bundle() == 'programme_filter') {
        $programmeFilter = new programmeFilter($entity->id());
        $programmeFilter->updateAllProgrammes();
    }
}