<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\epg\Controller\epgController;
use Drupal\epg\Model\Content\programmeFilter;

function epg_node_update(EntityInterface $entity)
{
    if ($entity->bundle() == 'programme_filter') {
        $programmeFilter = new programmeFilter($entity->id());
        $programmeFilter->updateAllProgrammes();
    }
}

function epg_last_import_cron() {
    $epgController = new epgController();
    $epgController->importFeed();
}

function epg_last_export_cron() {
    $epgController = new epgController();
    $epgController->createXML();
}

function epg_last_update_cron() {
    $epgController = new epgController();
    $epgController->importProviderData();
}